###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: [jekyll-feed]

###############################################################################
# Page Personal Details
url: https://xuyuanchi.github.io/
baseurl: /
author: 许愿池
title: 许愿池 | Welcome to my homepage
description: Personal Landing Page
avatar: photo.jpeg

# Contacts
email: suyanchi@gmail.com

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Social Usernames for Twitter, Github, Medium, Linkedin
username: 许愿池

# Research Outputs
google_scholar: 
orcid: 

# Google Analytics
google_analytics: 
