[[news]]
date = "2026-05"
content = "Our works, BRIDGE and scMAGCA, have been published in Nature Communications. Congratulations to Yubo and Yunhe 🎉"

[[news]]
date = "2026-04"
content = "I‘m very happy to be joining Professor Liu's lab at NUS as a Research Fellow 😊"

[[news]]
date = "2026-03"
content = "Our work OmiDos has been accepted by PNAS. Congratulations to Fan Yi 🎉"

[[news]]
date = "2026-03"
content = "Our work PAIR has been accepted by Advanced Science. Congratulations to myself 🎉"

[[news]]
date = "2025-12"
content = "Our work scSuperAnnotator has been accepted by NAR. Congratulations to Qi Qi and me 🎉"

[[news]]
date = "2025-11"
content = "Our work HMGDW has been accepted by IEEE JBHI 🎉"

[[news]]
date = "2025-09"
content = "Our work scMHVA has been accepted by Advanced Science. Congratulations to Yinan and me 🎉"
